# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "web01" do |web|
    web.vm.box = "ubuntu/bionic64"
    web.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
    web.vm.hostname = "web01"
    web.vm.network "private_network", ip:"192.168.115.10"
    web.vm.network "forwarded_port", guest:10000, host:10000
    web.vm.provision "shell", path:"web.sh"
  end
end
